In [5]:
import pandas as pd

In [11]:
df=pd.read_parquet("distribution/prnewswire.parquet")

In [12]:
df

               Word      logP    log1-P      logQ    log1-Q
0             realm -9.526002 -0.000073 -3.942347 -0.019593
1      underscoring -9.526002 -0.000073 -4.642684 -0.009678
2       solidifying -9.708324 -0.000061 -5.074261 -0.006275
3          esteemed -8.919867 -0.000134 -4.330058 -0.013254
4         endeavors -9.526002 -0.000073 -4.935189 -0.007215
...             ...       ...       ...       ...       ...
15132           our -2.463811 -0.088951 -6.420114 -0.001630
15133        differ -5.228717 -0.005375 -9.440539 -0.000079
15134       because -5.265673 -0.005179 -9.728221 -0.000060
15135        please -4.732970 -0.008839 -9.440539 -0.000079
15136            we -2.562182 -0.080274 -7.215915 -0.000735

[15137 rows x 5 columns]